// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridassets

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Input struct {
	Character character.Identifier `path:"character_id"`
	Page      *int32               `query:"page"`
}
