// Code generated by cmd/generate-request; DO NOT EDIT.

package getsovereigntysystems

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/alliance"
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
	"github.com/eve-online-tools/lib-esi-go/common/faction"
	"github.com/eve-online-tools/lib-esi-go/common/item"
	"github.com/eve-online-tools/lib-esi-go/common/solarsystem"
)

type Output struct {
	SolarSystems []SovereigntySystemsSolarsystem `json:"solar_systems"`
}

type SovereigntySystemsFaction struct {
	Faction faction.Identifier `json:"faction_id"`
}

type SovereigntySystemsDevelopment struct {
	ActivityDefenseMultiplier float64 `json:"activity_defense_multiplier"`
	IndustrialLevel           int64   `json:"industrial_level"`
	MilitaryLevel             int64   `json:"military_level"`
	StrategicLevel            int64   `json:"strategic_level"`
}

type SovereigntySystemsVulnerabilitywindow struct {
	End   time.Time `json:"end"`
	Start time.Time `json:"start"`
}

type SovereigntySystemsSovereigntyhub struct {
	Id                  item.Identifier                        `json:"id"`
	VulnerabilityWindow *SovereigntySystemsVulnerabilitywindow `json:"vulnerability_window"`
}

type SovereigntySystemsAlliance struct {
	Alliance        alliance.Identifier              `json:"alliance_id"`
	ClaimedSince    time.Time                        `json:"claimed_since"`
	Corporation     corporation.Identifier           `json:"corporation_id"`
	Development     SovereigntySystemsDevelopment    `json:"development"`
	IsCapitalSystem bool                             `json:"is_capital_system"`
	SovereigntyHub  SovereigntySystemsSovereigntyhub `json:"sovereignty_hub"`
}

type Claim struct {
	Faction   *SovereigntySystemsFaction  `json:"faction,omitempty"`
	Alliance  *SovereigntySystemsAlliance `json:"alliance,omitempty"`
	Unclaimed *bool                       `json:"unclaimed,omitempty"`
}

type SovereigntySystemsSolarsystem struct {
	Claim       Claim                  `json:"claim"`
	SolarSystem solarsystem.Identifier `json:"solar_system_id"`
}
