// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidstandings

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/corporations/{corporation_id}/standings",
	request.WithRequiredScope("esi-corporations.read_standings.v1"),
)
