// Code generated by cmd/generate-request; DO NOT EDIT.

package getmilitarycampaignsobjectiveslisting

import (
	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Input struct {
	After      *string   `query:"after"`
	Before     *string   `query:"before"`
	Limit      *int64    `query:"limit"`
	CampaignId uuid.UUID `path:"campaign_id"`
}
