// Code generated by cmd/generate-request; DO NOT EDIT.

package getmilitarycampaignsobjectiveslisting

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Output struct {
	Cursor     *Cursor                                      `json:"cursor"`
	Objectives []MilitaryCampaignsObjectivesDetailObjective `json:"objectives"`
}

type Cursor struct {
	After  *string `json:"after"`
	Before *string `json:"before"`
}

type MilitaryCampaignsObjectivesDetailParticipants struct {
	Committed    int64 `json:"committed"`
	Contributors int64 `json:"contributors"`
	Total        int64 `json:"total"`
}

type MilitaryCampaignsObjectivesDetailObjective struct {
	Finished     *time.Time                                    `json:"finished"`
	Id           uuid.UUID                                     `json:"id"`
	LastModified time.Time                                     `json:"last_modified"`
	Participants MilitaryCampaignsObjectivesDetailParticipants `json:"participants"`
	Progress     int64                                         `json:"progress"`
	Started      *time.Time                                    `json:"started"`
	State        string                                        `json:"state"`
}
