// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridtitles

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/characters/{character_id}/titles",
	request.WithRequiredScope("esi-characters.read_titles.v1"),
)
