// Code generated by cmd/generate-request; DO NOT EDIT.

package postcharacterscharacteridmail

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Input struct {
	Character    character.Identifier `path:"character_id"`
	ApprovedCost *int64               `body:"json"`
	Body         string               `body:"json" required:"true"`
	Recipients   []Recipients         `body:"json" required:"true"`
	Subject      string               `body:"json" required:"true"`
}

type Recipients struct {
	RecipientId   int64  `json:"recipient_id" required:"true"`
	RecipientType string `json:"recipient_type" required:"true"`
}
