// Code generated by cmd/generate-request; DO NOT EDIT.

package postcharacterscharacteridmail

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, Output](
	http.MethodPost,
	"/characters/{character_id}/mail",
	request.WithRequiredScope("esi-mail.send_mail.v1"),
)
