// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridordershistory

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/characters/{character_id}/orders/history",
	request.WithRequiredScope("esi-markets.read_character_orders.v1"),
)
