// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridimplants

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, Output](
	http.MethodGet,
	"/characters/{character_id}/implants",
	request.WithRequiredScope("esi-clones.read_implants.v1"),
)
