// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidindustryjobs

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/corporations/{corporation_id}/industry/jobs",
	request.WithRequiredScope("esi-industry.read_corporation_jobs.v1"),
)
