// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidmemberslimit

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, Output](
	http.MethodGet,
	"/corporations/{corporation_id}/members/limit",
	request.WithRequiredScope("esi-corporations.track_members.v1"),
)
