// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridmining

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/characters/{character_id}/mining",
	request.WithRequiredScope("esi-industry.read_character_mining.v1"),
)
