// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersdetail

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/alliance"
	"github.com/eve-online-tools/lib-esi-go/common/bloodline"
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
	"github.com/eve-online-tools/lib-esi-go/common/faction"
	"github.com/eve-online-tools/lib-esi-go/common/race"
	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Output struct {
	AchievementScore int64                  `json:"achievement_score"`
	Alliance         *alliance.Identifier   `json:"alliance_id"`
	Birthday         time.Time              `json:"birthday"`
	Bloodline        bloodline.Identifier   `json:"bloodline_id"`
	CharacterTitleId *uuid.UUID             `json:"character_title_id"`
	Corporation      corporation.Identifier `json:"corporation_id"`
	CorporationTitle *string                `json:"corporation_title"`
	Description      *string                `json:"description"`
	Faction          *faction.Identifier    `json:"faction_id"`
	Gender           string                 `json:"gender"`
	Name             string                 `json:"name"`
	Race             race.Identifier        `json:"race_id"`
	SecurityStatus   *float64               `json:"security_status"`
}
