// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridclones

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/characters/{character_id}/clones",
	request.WithRequiredScope("esi-clones.read_clones.v1"),
)
