// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersmilitarycampaignsobjectiveslisting

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Output struct {
	Cursor     *Cursor                                                                `json:"cursor"`
	Objectives []CharactersMilitaryCampaignsObjectivesParticipationCharacterobjective `json:"objectives"`
}

type Cursor struct {
	After  *string `json:"after"`
	Before *string `json:"before"`
}

type CharactersMilitaryCampaignsObjectivesParticipationCharacterobjective struct {
	CampaignId   uuid.UUID `json:"campaign_id"`
	Contributed  int64     `json:"contributed"`
	Id           uuid.UUID `json:"id"`
	IsCommitted  bool      `json:"is_committed"`
	LastModified time.Time `json:"last_modified"`
}
