// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersmercenarytacticaloperationsdetail

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Input struct {
	OperationId uuid.UUID            `path:"operation_id"`
	Character   character.Identifier `path:"character_id"`
}
