// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersmercenarytacticaloperationsdetail

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/dungeon"
	"github.com/eve-online-tools/lib-esi-go/common/item"
	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Output struct {
	DungeonType  dungeon.Identifier `json:"dungeon_type_id"`
	Expires      time.Time          `json:"expires"`
	Id           uuid.UUID          `json:"id"`
	MercenaryDen item.Identifier    `json:"mercenary_den_id"`
	State        string             `json:"state"`
}
