// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersmercenarytacticaloperationsdetail

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/characters/{character_id}/mercenary-tactical-operations/{operation_id}",
	request.WithRequiredScope("esi-activities.read_character.v1"),
)
