// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridroles

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/characters/{character_id}/roles",
	request.WithRequiredScope("esi-characters.read_corporation_roles.v1"),
)
