// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridindustryjobs

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Input struct {
	Character        character.Identifier `path:"character_id"`
	IncludeCompleted *bool                `query:"include_completed"`
}
