// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationcorporationidminingobservers

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/corporation/{corporation_id}/mining/observers",
	request.WithRequiredScope("esi-industry.read_corporation_mining.v1"),
)
