// Code generated by cmd/generate-request; DO NOT EDIT.

package getmilitarycampaignsobjectivesdetail

import (
	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Input struct {
	CampaignId  uuid.UUID `path:"campaign_id"`
	ObjectiveId uuid.UUID `path:"objective_id"`
}
