// Code generated by cmd/generate-request; DO NOT EDIT.

package getmilitarycampaignsobjectivesdetail

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/military-campaigns/{campaign_id}/objectives/{objective_id}",
)
