// Code generated by cmd/generate-request; DO NOT EDIT.

package getmetacompatibilitydates

import (
	"github.com/eve-online-tools/lib-esi-go/common/compatibilitydate"
)

type Output struct {
	CompatibilityDates []compatibilitydate.CompatibilityDate `json:"compatibility_dates"`
}
