// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridagentsresearch

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/characters/{character_id}/agents_research",
	request.WithRequiredScope("esi-characters.read_agents_research.v1"),
)
