// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsstructuressovereigntyhubsdetail

import (
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
	"github.com/eve-online-tools/lib-esi-go/common/item"
)

type Input struct {
	SovereigntyHub item.Identifier        `path:"sovereignty_hub_id"`
	Corporation    corporation.Identifier `path:"corporation_id"`
}
