// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsstructuressovereigntyhubsdetail

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/accesslist"
	"github.com/eve-online-tools/lib-esi-go/common/item"
	"github.com/eve-online-tools/lib-esi-go/common/solarsystem"
	"github.com/eve-online-tools/lib-esi-go/common/typeid"
)

type Output struct {
	FuelAccessList      *accesslist.Identifier                                          `json:"fuel_access_list_id"`
	Id                  item.Identifier                                                 `json:"id"`
	ReagentBay          CorporationsStructuresSovereigntyHubsDetailReagentbay           `json:"reagent_bay"`
	Resources           CorporationsStructuresSovereigntyHubsDetailResources            `json:"resources"`
	SolarSystem         solarsystem.Identifier                                          `json:"solar_system_id"`
	Upgrades            []CorporationsStructuresSovereigntyHubsDetailUpgrade            `json:"upgrades"`
	VulnerabilityWindow *CorporationsStructuresSovereigntyHubsDetailVulnerabilitywindow `json:"vulnerability_window"`
	WorkforceTransport  CorporationsStructuresSovereigntyHubsDetailTransport            `json:"workforce_transport"`
}

type CorporationsStructuresSovereigntyHubsDetailReagent struct {
	Amount         int64             `json:"amount"`
	BurningPerHour int64             `json:"burning_per_hour"`
	Type           typeid.Identifier `json:"type_id"`
}

type CorporationsStructuresSovereigntyHubsDetailReagentbay struct {
	LastUpdated time.Time                                            `json:"last_updated"`
	Reagents    []CorporationsStructuresSovereigntyHubsDetailReagent `json:"reagents"`
}

type CorporationsStructuresSovereigntyHubsDetailResourcepower struct {
	Allocated int64 `json:"allocated"`
	Available int64 `json:"available"`
}

type CorporationsStructuresSovereigntyHubsDetailResourceworkforce struct {
	Allocated int64 `json:"allocated"`
	Available int64 `json:"available"`
}

type CorporationsStructuresSovereigntyHubsDetailResources struct {
	Power     CorporationsStructuresSovereigntyHubsDetailResourcepower     `json:"power"`
	Workforce CorporationsStructuresSovereigntyHubsDetailResourceworkforce `json:"workforce"`
}

type CorporationsStructuresSovereigntyHubsDetailUpgrade struct {
	PowerState string            `json:"power_state"`
	Type       typeid.Identifier `json:"type_id"`
}

type CorporationsStructuresSovereigntyHubsDetailVulnerabilitywindow struct {
	End   time.Time `json:"end"`
	Start time.Time `json:"start"`
}

type CorporationsStructuresSovereigntyHubsDetailTransportconfigurationsource struct {
	SolarSystem solarsystem.Identifier `json:"solar_system_id"`
}

type CorporationsStructuresSovereigntyHubsDetailTransportconfigurationimport struct {
	Sources []CorporationsStructuresSovereigntyHubsDetailTransportconfigurationsource `json:"sources"`
}

type CorporationsStructuresSovereigntyHubsDetailTransportconfigurationexport struct {
	Amount      int64                   `json:"amount"`
	SolarSystem *solarsystem.Identifier `json:"solar_system_id"`
}

type Configuration struct {
	Import  *CorporationsStructuresSovereigntyHubsDetailTransportconfigurationimport `json:"import,omitempty"`
	Export  *CorporationsStructuresSovereigntyHubsDetailTransportconfigurationexport `json:"export,omitempty"`
	Transit *bool                                                                    `json:"transit,omitempty"`
}

type CorporationsStructuresSovereigntyHubsDetailTransportstateimportsource struct {
	Amount      int64                  `json:"amount"`
	SolarSystem solarsystem.Identifier `json:"solar_system_id"`
}

type CorporationsStructuresSovereigntyHubsDetailTransportstateimport struct {
	Sources []CorporationsStructuresSovereigntyHubsDetailTransportstateimportsource `json:"sources"`
}

type CorporationsStructuresSovereigntyHubsDetailTransportstateexport struct {
	Amount      *int64                  `json:"amount"`
	SolarSystem *solarsystem.Identifier `json:"solar_system_id"`
}

type State struct {
	Import  *CorporationsStructuresSovereigntyHubsDetailTransportstateimport `json:"import,omitempty"`
	Export  *CorporationsStructuresSovereigntyHubsDetailTransportstateexport `json:"export,omitempty"`
	Transit *bool                                                            `json:"transit,omitempty"`
}

type CorporationsStructuresSovereigntyHubsDetailTransport struct {
	Configuration Configuration `json:"configuration"`
	State         State         `json:"state"`
}
