// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridcontractscontractiditems

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Input struct {
	Character  character.Identifier `path:"character_id"`
	ContractId int64                `path:"contract_id"`
}
