// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridfittings

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/characters/{character_id}/fittings",
	request.WithRequiredScope("esi-fittings.read_fittings.v1"),
)
