// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationcorporationidminingobserversobserverid

import (
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
)

type Input struct {
	Corporation corporation.Identifier `path:"corporation_id"`
	ObserverId  int64                  `path:"observer_id"`
	Page        *int32                 `query:"page"`
}
