// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidmembers

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, Output](
	http.MethodGet,
	"/corporations/{corporation_id}/members",
	request.WithRequiredScope("esi-corporations.read_corporation_membership.v1"),
)
