// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersparagonhubskinr

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/alliance"
	"github.com/eve-online-tools/lib-esi-go/common/character"
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Output struct {
	Cursor   *Cursor                         `json:"cursor"`
	Listings []CharactersParagonHubSkinrItem `json:"listings"`
}

type Cursor struct {
	After  *string `json:"after"`
	Before *string `json:"before"`
}

type Price struct {
	Isk  *float64 `json:"isk,omitempty"`
	Plex *int64   `json:"plex,omitempty"`
}

type Target struct {
	Character   *character.Identifier   `json:"character_id,omitempty"`
	Corporation *corporation.Identifier `json:"corporation_id,omitempty"`
	Alliance    *alliance.Identifier    `json:"alliance_id,omitempty"`
	Public      *bool                   `json:"public,omitempty"`
}

type CharactersParagonHubSkinrItem struct {
	Created      time.Time            `json:"created"`
	Expires      time.Time            `json:"expires"`
	Id           uuid.UUID            `json:"id"`
	LastModified time.Time            `json:"last_modified"`
	Price        Price                `json:"price"`
	Quantity     int64                `json:"quantity"`
	Seller       character.Identifier `json:"seller_id"`
	SkinrId      string               `json:"skinr_id"`
	State        string               `json:"state"`
	Target       Target               `json:"target"`
}
