// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersparagonhubskinr

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/characters/{character_id}/paragon-hub/skinr",
	request.WithRequiredScope("esi.cosmetic.char:read"),
)
