// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridmaillists

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/characters/{character_id}/mail/lists",
	request.WithRequiredScope("esi-mail.read_mail.v1"),
)
