// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridskillqueue

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/typeid"
)

type Output struct {
	FinishDate      *time.Time        `json:"finish_date"`
	FinishedLevel   int64             `json:"finished_level"`
	LevelEndSp      *int64            `json:"level_end_sp"`
	LevelStartSp    *int64            `json:"level_start_sp"`
	QueuePosition   int64             `json:"queue_position"`
	Skill           typeid.Identifier `json:"skill_id"`
	StartDate       *time.Time        `json:"start_date"`
	TrainingStartSp *int64            `json:"training_start_sp"`
}
