// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridskillqueue

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/characters/{character_id}/skillqueue",
	request.WithRequiredScope("esi-skills.read_skillqueue.v1"),
)
