// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidcontainerslogs

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/corporations/{corporation_id}/containers/logs",
	request.WithRequiredScope("esi-corporations.read_container_logs.v1"),
)
