// Code generated by cmd/generate-request; DO NOT EDIT.

package putfleetsfleetidsquadssquadid

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, struct{}](
	http.MethodPut,
	"/fleets/{fleet_id}/squads/{squad_id}",
	request.WithRequiredScope("esi-fleets.write_fleet.v1"),
)
