// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsnpccorps

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.CreateStatic[Output](
	http.MethodGet,
	"/corporations/npccorps",
)
