// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersstructuresmercenarydensdetail

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/corporation"
	"github.com/eve-online-tools/lib-esi-go/common/item"
	"github.com/eve-online-tools/lib-esi-go/common/planet"
	"github.com/eve-online-tools/lib-esi-go/common/typeid"
)

type Output struct {
	Evolution          CharactersStructuresMercenaryDensDetailEvolution           `json:"evolution"`
	Id                 item.Identifier                                            `json:"id"`
	Infomorphs         CharactersStructuresMercenaryDensDetailInfomorphs          `json:"infomorphs"`
	ReinforcementTimer *CharactersStructuresMercenaryDensDetailReinforcementtimer `json:"reinforcement_timer"`
	Skyhook            CharactersStructuresMercenaryDensDetailSkyhook             `json:"skyhook"`
	State              string                                                     `json:"state"`
	Type               typeid.Identifier                                          `json:"type_id"`
}

type CharactersStructuresMercenaryDensDetailEvolutionanarchy struct {
	Amount int64  `json:"amount"`
	Level  string `json:"level"`
}

type CharactersStructuresMercenaryDensDetailEvolutiondevelopment struct {
	Amount int64  `json:"amount"`
	Level  string `json:"level"`
}

type CharactersStructuresMercenaryDensDetailEvolution struct {
	Anarchy     CharactersStructuresMercenaryDensDetailEvolutionanarchy     `json:"anarchy"`
	Development CharactersStructuresMercenaryDensDetailEvolutiondevelopment `json:"development"`
}

type CharactersStructuresMercenaryDensDetailInfomorphs struct {
	Amount int64 `json:"amount"`
}

type CharactersStructuresMercenaryDensDetailReinforcementtimer struct {
	End time.Time `json:"end"`
}

type CharactersStructuresMercenaryDensDetailSkyhook struct {
	Corporation corporation.Identifier `json:"corporation_id"`
	Id          item.Identifier        `json:"id"`
	Planet      planet.Identifier      `json:"planet_id"`
}
