// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersstructuresmercenarydensdetail

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/characters/{character_id}/structures/mercenary-dens/{mercenary_den_id}",
	request.WithRequiredScope("esi-structures.read_character.v1"),
)
