// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidkillmailsrecent

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/corporations/{corporation_id}/killmails/recent",
	request.WithRequiredScope("esi-killmails.read_corporation_killmails.v1"),
)
