// Code generated by cmd/generate-request; DO NOT EDIT.

package deletecharacterscharacteridfittingsfittingid

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, struct{}](
	http.MethodDelete,
	"/characters/{character_id}/fittings/{fitting_id}",
	request.WithRequiredScope("esi-fittings.write_fittings.v1"),
)
