// Code generated by cmd/generate-request; DO NOT EDIT.

package postuiautopilotwaypoint

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, struct{}](
	http.MethodPost,
	"/ui/autopilot/waypoint",
	request.WithRequiredScope("esi-ui.write_waypoint.v1"),
)
