// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidcontracts

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/corporations/{corporation_id}/contracts",
	request.WithRequiredScope("esi-contracts.read_corporation_contracts.v1"),
)
