// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eve-online-tools/lib-esi-go/middleware/authentication (interfaces: Token,RefreshableToken,ScopedToken)
//
// Generated by this command:
//
//	mockgen -build_flags=--mod=mod -destination=mock/mock_token.go -package=mock github.com/eve-online-tools/lib-esi-go/middleware/authentication Token,RefreshableToken,ScopedToken
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockToken is a mock of Token interface.
type MockToken struct {
	ctrl     *gomock.Controller
	recorder *MockTokenMockRecorder
	isgomock struct{}
}

// MockTokenMockRecorder is the mock recorder for MockToken.
type MockTokenMockRecorder struct {
	mock *MockToken
}

// NewMockToken creates a new mock instance.
func NewMockToken(ctrl *gomock.Controller) *MockToken {
	mock := &MockToken{ctrl: ctrl}
	mock.recorder = &MockTokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToken) EXPECT() *MockTokenMockRecorder {
	return m.recorder
}

// Owner mocks base method.
func (m *MockToken) Owner() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Owner")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Owner indicates an expected call of Owner.
func (mr *MockTokenMockRecorder) Owner() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Owner", reflect.TypeOf((*MockToken)(nil).Owner))
}

// Token mocks base method.
func (m *MockToken) Token() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token")
	ret0, _ := ret[0].(string)
	return ret0
}

// Token indicates an expected call of Token.
func (mr *MockTokenMockRecorder) Token() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockToken)(nil).Token))
}

// MockRefreshableToken is a mock of RefreshableToken interface.
type MockRefreshableToken struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshableTokenMockRecorder
	isgomock struct{}
}

// MockRefreshableTokenMockRecorder is the mock recorder for MockRefreshableToken.
type MockRefreshableTokenMockRecorder struct {
	mock *MockRefreshableToken
}

// NewMockRefreshableToken creates a new mock instance.
func NewMockRefreshableToken(ctrl *gomock.Controller) *MockRefreshableToken {
	mock := &MockRefreshableToken{ctrl: ctrl}
	mock.recorder = &MockRefreshableTokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshableToken) EXPECT() *MockRefreshableTokenMockRecorder {
	return m.recorder
}

// Owner mocks base method.
func (m *MockRefreshableToken) Owner() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Owner")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Owner indicates an expected call of Owner.
func (mr *MockRefreshableTokenMockRecorder) Owner() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Owner", reflect.TypeOf((*MockRefreshableToken)(nil).Owner))
}

// RefreshIfNeeded mocks base method.
func (m *MockRefreshableToken) RefreshIfNeeded(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshIfNeeded", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshIfNeeded indicates an expected call of RefreshIfNeeded.
func (mr *MockRefreshableTokenMockRecorder) RefreshIfNeeded(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshIfNeeded", reflect.TypeOf((*MockRefreshableToken)(nil).RefreshIfNeeded), ctx)
}

// Token mocks base method.
func (m *MockRefreshableToken) Token() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token")
	ret0, _ := ret[0].(string)
	return ret0
}

// Token indicates an expected call of Token.
func (mr *MockRefreshableTokenMockRecorder) Token() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockRefreshableToken)(nil).Token))
}

// MockScopedToken is a mock of ScopedToken interface.
type MockScopedToken struct {
	ctrl     *gomock.Controller
	recorder *MockScopedTokenMockRecorder
	isgomock struct{}
}

// MockScopedTokenMockRecorder is the mock recorder for MockScopedToken.
type MockScopedTokenMockRecorder struct {
	mock *MockScopedToken
}

// NewMockScopedToken creates a new mock instance.
func NewMockScopedToken(ctrl *gomock.Controller) *MockScopedToken {
	mock := &MockScopedToken{ctrl: ctrl}
	mock.recorder = &MockScopedTokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScopedToken) EXPECT() *MockScopedTokenMockRecorder {
	return m.recorder
}

// Owner mocks base method.
func (m *MockScopedToken) Owner() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Owner")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Owner indicates an expected call of Owner.
func (mr *MockScopedTokenMockRecorder) Owner() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Owner", reflect.TypeOf((*MockScopedToken)(nil).Owner))
}

// Scopes mocks base method.
func (m *MockScopedToken) Scopes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scopes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Scopes indicates an expected call of Scopes.
func (mr *MockScopedTokenMockRecorder) Scopes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scopes", reflect.TypeOf((*MockScopedToken)(nil).Scopes))
}

// Token mocks base method.
func (m *MockScopedToken) Token() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token")
	ret0, _ := ret[0].(string)
	return ret0
}

// Token indicates an expected call of Token.
func (mr *MockScopedTokenMockRecorder) Token() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockScopedToken)(nil).Token))
}
