// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridwallettransactions

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Input struct {
	Character character.Identifier `path:"character_id"`
	FromId    *int64               `query:"from_id"`
}
