// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersaccesslistslisting

import (
	"github.com/eve-online-tools/lib-esi-go/common/accesslist"
)

type Output struct {
	AccessLists []CharactersAccessListsListingAccesslist `json:"access_lists"`
}

type CharactersAccessListsListingAccesslist struct {
	Id accesslist.Identifier `json:"id"`
}
