// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersaccesslistsdetail

import (
	"github.com/eve-online-tools/lib-esi-go/common/accesslist"
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Input struct {
	AccessList accesslist.Identifier `path:"access_list_id"`
	Character  character.Identifier  `path:"character_id"`
}
