// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersaccesslistsdetail

import (
	"github.com/eve-online-tools/lib-esi-go/common/accesslist"
	"github.com/eve-online-tools/lib-esi-go/common/alliance"
	"github.com/eve-online-tools/lib-esi-go/common/character"
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
)

type Output struct {
	Description string                                `json:"description"`
	Id          accesslist.Identifier                 `json:"id"`
	Membership  CharactersAccessListsDetailMembership `json:"membership"`
	Name        string                                `json:"name"`
}

type CharactersAccessListsDetailAllianceentry struct {
	Access   string              `json:"access"`
	Alliance alliance.Identifier `json:"alliance_id"`
}

type CharactersAccessListsDetailCharacterentry struct {
	Access    string               `json:"access"`
	Character character.Identifier `json:"character_id"`
}

type CharactersAccessListsDetailCorporationentry struct {
	Access      string                 `json:"access"`
	Corporation corporation.Identifier `json:"corporation_id"`
}

type CharactersAccessListsDetailMembership struct {
	Alliances     []CharactersAccessListsDetailAllianceentry    `json:"alliances"`
	AllowEveryone bool                                          `json:"allow_everyone"`
	Characters    []CharactersAccessListsDetailCharacterentry   `json:"characters"`
	Corporations  []CharactersAccessListsDetailCorporationentry `json:"corporations"`
}
