// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersaccesslistsdetail

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/characters/{character_id}/access-lists/{access_list_id}",
	request.WithRequiredScope("esi-access.read_lists.v1"),
)
