// Code generated by cmd/generate-request; DO NOT EDIT.

package postcorporationscorporationidassetslocations

import (
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
)

type Input struct {
	Corporation corporation.Identifier `path:"corporation_id"`
	Body        []int64                `body:"json" required:"true"`
}
