// Code generated by cmd/generate-request; DO NOT EDIT.

package postcorporationscorporationidassetslocations

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodPost,
	"/corporations/{corporation_id}/assets/locations",
	request.WithRequiredScope("esi-assets.read_corporation_assets.v1"),
)
