// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridplanetsplanetid

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/characters/{character_id}/planets/{planet_id}",
	request.WithRequiredScope("esi-planets.manage_planets.v1"),
)
