// Code generated by cmd/generate-request; DO NOT EDIT.

package putcharacterscharacteridcalendareventid

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Input struct {
	Character character.Identifier `path:"character_id"`
	EventId   int64                `path:"event_id"`
	Response  string               `body:"json" required:"true"`
}
