// Code generated by cmd/generate-request; DO NOT EDIT.

package putcharacterscharacteridcalendareventid

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, struct{}](
	http.MethodPut,
	"/characters/{character_id}/calendar/{event_id}",
	request.WithRequiredScope("esi-calendar.respond_calendar_events.v1"),
)
