// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridcalendar

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Input struct {
	Character character.Identifier `path:"character_id"`
	FromEvent *int64               `query:"from_event"`
}
