// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridcalendar

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/characters/{character_id}/calendar",
	request.WithRequiredScope("esi-calendar.read_calendar_events.v1"),
)
