// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidcustomsoffices

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/corporations/{corporation_id}/customs_offices",
	request.WithRequiredScope("esi-planets.read_customs_offices.v1"),
)
