// Code generated by cmd/generate-request; DO NOT EDIT.

package getalliancesallianceid

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/character"
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
	"github.com/eve-online-tools/lib-esi-go/common/faction"
)

type Output struct {
	CreatorCorporation  corporation.Identifier  `json:"creator_corporation_id"`
	Creator             character.Identifier    `json:"creator_id"`
	DateFounded         time.Time               `json:"date_founded"`
	ExecutorCorporation *corporation.Identifier `json:"executor_corporation_id"`
	Faction             *faction.Identifier     `json:"faction_id"`
	Name                string                  `json:"name"`
	Ticker              string                  `json:"ticker"`
}
