// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsfreelancejobsparticipants

import (
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Input struct {
	After       *string                `query:"after"`
	Before      *string                `query:"before"`
	Limit       *int64                 `query:"limit"`
	Corporation corporation.Identifier `path:"corporation_id"`
	JobId       uuid.UUID              `path:"job_id"`
}
