// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsfreelancejobsparticipants

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Output struct {
	Cursor       *Cursor                                            `json:"cursor"`
	Participants []CorporationsFreelanceJobsParticipantsParticipant `json:"participants"`
}

type Cursor struct {
	After  *string `json:"after"`
	Before *string `json:"before"`
}

type CorporationsFreelanceJobsParticipantsParticipant struct {
	Contributed int64                `json:"contributed"`
	Id          character.Identifier `json:"id"`
	Name        string               `json:"name"`
	State       string               `json:"state"`
}
