// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidstarbasesstarbaseid

import (
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
)

type Input struct {
	Corporation corporation.Identifier `path:"corporation_id"`
	StarbaseId  int64                  `path:"starbase_id"`
	SystemId    int64                  `query:"system_id" required:"true"`
}
