// Code generated by cmd/generate-request; DO NOT EDIT.

package getfreelancejobslisting

import (
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
)

type Input struct {
	After       *string                 `query:"after"`
	Before      *string                 `query:"before"`
	Limit       *int64                  `query:"limit"`
	Corporation *corporation.Identifier `query:"corporation_id"`
}
