// Code generated by cmd/generate-request; DO NOT EDIT.

package getloyaltystorescorporationidoffers

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/loyalty/stores/{corporation_id}/offers",
)
