// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridlocation

import (
	"github.com/eve-online-tools/lib-esi-go/common/item"
	"github.com/eve-online-tools/lib-esi-go/common/solarsystem"
	"github.com/eve-online-tools/lib-esi-go/common/station"
)

type Output struct {
	SolarSystem solarsystem.Identifier `json:"solar_system_id"`
	Station     *station.Identifier    `json:"station_id"`
	Structure   *item.Identifier       `json:"structure_id"`
}
