// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridlocation

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/characters/{character_id}/location",
	request.WithRequiredScope("esi-location.read_location.v1"),
)
