// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsprojectscontributors

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Output struct {
	Contributors []CorporationsProjectsContributorsContributor `json:"contributors"`
	Cursor       *Cursor                                       `json:"cursor"`
}

type CorporationsProjectsContributorsContributor struct {
	Contributed int64                `json:"contributed"`
	Id          character.Identifier `json:"id"`
	Name        string               `json:"name"`
}

type Cursor struct {
	After  *string `json:"after"`
	Before *string `json:"before"`
}
