// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsprojectscontributors

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/corporations/{corporation_id}/projects/{project_id}/contributors",
	request.WithRequiredScope("esi-corporations.read_projects.v1"),
)
