// Code generated by cmd/generate-request; DO NOT EDIT.

package getmilitarycampaignslisting

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Output struct {
	Campaigns []MilitaryCampaignsDetailCampaign `json:"campaigns"`
}

type MilitaryCampaignsDetailCampaign struct {
	Finished *time.Time `json:"finished"`
	Id       uuid.UUID  `json:"id"`
	Progress int64      `json:"progress"`
	Started  *time.Time `json:"started"`
	State    string     `json:"state"`
}
