// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsprojectsdetail

import (
	"encoding/json"
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/alliance"
	"github.com/eve-online-tools/lib-esi-go/common/archetype"
	"github.com/eve-online-tools/lib-esi-go/common/attribute"
	"github.com/eve-online-tools/lib-esi-go/common/character"
	"github.com/eve-online-tools/lib-esi-go/common/constellation"
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
	"github.com/eve-online-tools/lib-esi-go/common/faction"
	"github.com/eve-online-tools/lib-esi-go/common/group"
	"github.com/eve-online-tools/lib-esi-go/common/item"
	"github.com/eve-online-tools/lib-esi-go/common/region"
	"github.com/eve-online-tools/lib-esi-go/common/shiptreegroup"
	"github.com/eve-online-tools/lib-esi-go/common/solarsystem"
	"github.com/eve-online-tools/lib-esi-go/common/station"
	"github.com/eve-online-tools/lib-esi-go/common/typeid"
	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Output struct {
	Configuration Configuration                           `json:"configuration"`
	Contribution  *CorporationsProjectsDetailContribution `json:"contribution"`
	Creator       CorporationsProjectsDetailCreator       `json:"creator"`
	Details       CorporationsProjectsDetailDetails       `json:"details"`
	Id            uuid.UUID                               `json:"id"`
	LastModified  time.Time                               `json:"last_modified"`
	Name          string                                  `json:"name"`
	Progress      CorporationsProjectsDetailProgress      `json:"progress"`
	Reward        *CorporationsProjectsDetailReward       `json:"reward"`
	State         string                                  `json:"state"`
}

type CorporationsProjectsDetailConfigurationmatcherarchetype struct {
	Archetype *archetype.Identifier `json:"archetype_id"`
}

type CorporationsProjectsDetailConfigurationmatcherfaction struct {
	Faction *faction.Identifier `json:"faction_id"`
}

type Location struct {
	SolarSystem   *solarsystem.Identifier   `json:"solar_system_id,omitempty"`
	Constellation *constellation.Identifier `json:"constellation_id,omitempty"`
	Region        *region.Identifier        `json:"region_id,omitempty"`
}

type CorporationsProjectsDetailConfigurationcapturefwcomplex struct {
	Archetypes []CorporationsProjectsDetailConfigurationmatcherarchetype `json:"archetypes"`
	Factions   []CorporationsProjectsDetailConfigurationmatcherfaction   `json:"factions"`
	Locations  []Location                                                `json:"locations"`
}

type Identity struct {
	Character   *character.Identifier   `json:"character_id,omitempty"`
	Corporation *corporation.Identifier `json:"corporation_id,omitempty"`
	Alliance    *alliance.Identifier    `json:"alliance_id,omitempty"`
	Faction     *faction.Identifier     `json:"faction_id,omitempty"`
}

type Ship struct {
	Type  *typeid.Identifier        `json:"type_id,omitempty"`
	Group *shiptreegroup.Identifier `json:"group_id,omitempty"`
}

type CorporationsProjectsDetailConfigurationdamageship struct {
	Identities []Identity `json:"identities"`
	Locations  []Location `json:"locations"`
	Ships      []Ship     `json:"ships"`
}

type CorporationsProjectsDetailConfigurationdefendfwcomplex struct {
	Archetypes []CorporationsProjectsDetailConfigurationmatcherarchetype `json:"archetypes"`
	Factions   []CorporationsProjectsDetailConfigurationmatcherfaction   `json:"factions"`
	Locations  []Location                                                `json:"locations"`
}

type DockingLocation struct {
	Structure *item.Identifier    `json:"structure_id,omitempty"`
	Station   *station.Identifier `json:"station_id,omitempty"`
}

type Item struct {
	Type  *typeid.Identifier `json:"type_id,omitempty"`
	Group *group.Identifier  `json:"group_id,omitempty"`
}

type CorporationsProjectsDetailConfigurationdeliveritem struct {
	DockingLocations []DockingLocation `json:"docking_locations"`
	Items            []Item            `json:"items"`
	Office           *item.Identifier  `json:"office_id"`
}

type CorporationsProjectsDetailConfigurationdestroynpc struct {
	Locations []Location `json:"locations"`
}

type CorporationsProjectsDetailConfigurationdestroyship struct {
	Identities []Identity `json:"identities"`
	Locations  []Location `json:"locations"`
	Ships      []Ship     `json:"ships"`
}

type CorporationsProjectsDetailConfigurationmatchercorporation struct {
	Corporation *corporation.Identifier `json:"corporation_id"`
}

type CorporationsProjectsDetailConfigurationearnloyaltypoints struct {
	Corporations []CorporationsProjectsDetailConfigurationmatchercorporation `json:"corporations"`
}

type CorporationsProjectsDetailConfigurationlostship struct {
	Identities []Identity `json:"identities"`
	Locations  []Location `json:"locations"`
	Ships      []Ship     `json:"ships"`
}

type CorporationsProjectsDetailConfigurationmanual struct {
}

type CorporationsProjectsDetailConfigurationmanufactureitem struct {
	DockingLocations []DockingLocation `json:"docking_locations"`
	Items            []Item            `json:"items"`
	Owner            string            `json:"owner"`
}

type Material struct {
	Type  *typeid.Identifier `json:"type_id,omitempty"`
	Group *group.Identifier  `json:"group_id,omitempty"`
}

type CorporationsProjectsDetailConfigurationminematerial struct {
	Locations []Location `json:"locations"`
	Materials []Material `json:"materials"`
}

type CorporationsProjectsDetailConfigurationremoteboostshield struct {
	Identities []Identity `json:"identities"`
	Locations  []Location `json:"locations"`
	Ships      []Ship     `json:"ships"`
}

type CorporationsProjectsDetailConfigurationremoterepairarmor struct {
	Identities []Identity `json:"identities"`
	Locations  []Location `json:"locations"`
	Ships      []Ship     `json:"ships"`
}

type CorporationsProjectsDetailConfigurationsalvagewreck struct {
	Locations []Location `json:"locations"`
}

type CorporationsProjectsDetailConfigurationmatchersignature struct {
	SignatureType *attribute.Identifier `json:"signature_type_id"`
}

type CorporationsProjectsDetailConfigurationscansignature struct {
	Locations  []Location                                                `json:"locations"`
	Signatures []CorporationsProjectsDetailConfigurationmatchersignature `json:"signatures"`
}

type CorporationsProjectsDetailConfigurationshipinsurance struct {
	ConflictType      string     `json:"conflict_type"`
	Identities        []Identity `json:"identities"`
	Locations         []Location `json:"locations"`
	ReimburseImplants bool       `json:"reimburse_implants"`
	Ships             []Ship     `json:"ships"`
}

type CorporationsProjectsDetailConfigurationunknown struct {
	Data json.RawMessage `json:"data"`
	Type string          `json:"type"`
}

type Configuration struct {
	CaptureFwComplex  *CorporationsProjectsDetailConfigurationcapturefwcomplex  `json:"capture_fw_complex,omitempty"`
	DamageShip        *CorporationsProjectsDetailConfigurationdamageship        `json:"damage_ship,omitempty"`
	DefendFwComplex   *CorporationsProjectsDetailConfigurationdefendfwcomplex   `json:"defend_fw_complex,omitempty"`
	DeliverItem       *CorporationsProjectsDetailConfigurationdeliveritem       `json:"deliver_item,omitempty"`
	DestroyNpc        *CorporationsProjectsDetailConfigurationdestroynpc        `json:"destroy_npc,omitempty"`
	DestroyShip       *CorporationsProjectsDetailConfigurationdestroyship       `json:"destroy_ship,omitempty"`
	EarnLoyaltyPoint  *CorporationsProjectsDetailConfigurationearnloyaltypoints `json:"earn_loyalty_point,omitempty"`
	LostShip          *CorporationsProjectsDetailConfigurationlostship          `json:"lost_ship,omitempty"`
	Manual            *CorporationsProjectsDetailConfigurationmanual            `json:"manual,omitempty"`
	ManufactureItem   *CorporationsProjectsDetailConfigurationmanufactureitem   `json:"manufacture_item,omitempty"`
	MineMaterial      *CorporationsProjectsDetailConfigurationminematerial      `json:"mine_material,omitempty"`
	RemoteBoostShield *CorporationsProjectsDetailConfigurationremoteboostshield `json:"remote_boost_shield,omitempty"`
	RemoteRepairArmor *CorporationsProjectsDetailConfigurationremoterepairarmor `json:"remote_repair_armor,omitempty"`
	SalvageWreck      *CorporationsProjectsDetailConfigurationsalvagewreck      `json:"salvage_wreck,omitempty"`
	ScanSignature     *CorporationsProjectsDetailConfigurationscansignature     `json:"scan_signature,omitempty"`
	ShipInsurance     *CorporationsProjectsDetailConfigurationshipinsurance     `json:"ship_insurance,omitempty"`
	Unknown           *CorporationsProjectsDetailConfigurationunknown           `json:"unknown,omitempty"`
}

type CorporationsProjectsDetailContribution struct {
	ParticipationLimit    *int64   `json:"participation_limit"`
	RewardPerContribution *float64 `json:"reward_per_contribution"`
	SubmissionLimit       *int64   `json:"submission_limit"`
	SubmissionMultiplier  *float64 `json:"submission_multiplier"`
}

type CorporationsProjectsDetailCreator struct {
	Id   character.Identifier `json:"id"`
	Name string               `json:"name"`
}

type CorporationsProjectsDetailDetails struct {
	Career      string     `json:"career"`
	Created     time.Time  `json:"created"`
	Description string     `json:"description"`
	Expires     *time.Time `json:"expires"`
	Finished    *time.Time `json:"finished"`
}

type CorporationsProjectsDetailProgress struct {
	Current int64 `json:"current"`
	Desired int64 `json:"desired"`
}

type CorporationsProjectsDetailReward struct {
	Initial   float64 `json:"initial"`
	Remaining float64 `json:"remaining"`
}
