// Code generated by cmd/generate-request; DO NOT EDIT.

package deletecharacterscharacteridmailmailid

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Input struct {
	Character character.Identifier `path:"character_id"`
	MailId    int64                `path:"mail_id"`
}
