// Code generated by cmd/generate-request; DO NOT EDIT.

package deletecharacterscharacteridmailmailid

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, struct{}](
	http.MethodDelete,
	"/characters/{character_id}/mail/{mail_id}",
	request.WithRequiredScope("esi-mail.organize_mail.v1"),
)
