// Code generated by cmd/generate-request; DO NOT EDIT.

package deletecharacterscharacteridmaillabelslabelid

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Input struct {
	Character character.Identifier `path:"character_id"`
	LabelId   int64                `path:"label_id"`
}
