// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationiddivisions

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/corporations/{corporation_id}/divisions",
	request.WithRequiredScope("esi-corporations.read_divisions.v1"),
)
