// Code generated by cmd/generate-request; DO NOT EDIT.

package postcharacterscharacteridfittings

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Input struct {
	Character   character.Identifier `path:"character_id"`
	Description string               `body:"json" required:"true"`
	Items       []Items              `body:"json" required:"true"`
	Name        string               `body:"json" required:"true"`
	ShipTypeId  int64                `body:"json" required:"true"`
}

type Items struct {
	Flag     string `json:"flag" required:"true"`
	Quantity int64  `json:"quantity" required:"true"`
	TypeId   int64  `json:"type_id" required:"true"`
}
