// Code generated by cmd/generate-request; DO NOT EDIT.

package postcharacterscharacteridfittings

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodPost,
	"/characters/{character_id}/fittings",
	request.WithRequiredScope("esi-fittings.write_fittings.v1"),
)
