// Code generated by cmd/generate-request; DO NOT EDIT.

package getalliancesallianceidcorporations

import (
	"github.com/eve-online-tools/lib-esi-go/common/alliance"
)

type Input struct {
	Alliance alliance.Identifier `path:"alliance_id"`
}
