// Code generated by cmd/generate-request; DO NOT EDIT.

package getalliancesallianceidcorporations

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, Output](
	http.MethodGet,
	"/alliances/{alliance_id}/corporations",
)
