// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersstructuresmercenarydenslisting

import (
	"github.com/eve-online-tools/lib-esi-go/common/item"
	"github.com/eve-online-tools/lib-esi-go/common/planet"
)

type Output struct {
	MercenaryDens []CharactersStructuresMercenaryDensListingMercenaryden `json:"mercenary_dens"`
}

type CharactersStructuresMercenaryDensListingMercenaryden struct {
	Id     item.Identifier   `json:"id"`
	Planet planet.Identifier `json:"planet_id"`
}
