// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidwalletsdivisiontransactions

import (
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
)

type Input struct {
	Corporation corporation.Identifier `path:"corporation_id"`
	Division    int64                  `path:"division"`
	FromId      *int64                 `query:"from_id"`
}
