// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidwalletsdivisiontransactions

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/corporations/{corporation_id}/wallets/{division}/transactions",
	request.WithRequiredScope("esi-wallet.read_corporation_wallets.v1"),
)
