// Code generated by cmd/generate-request; DO NOT EDIT.

package getkillmailskillmailidkillmailhash

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/killmails/{killmail_id}/{killmail_hash}",
)
