// Code generated by cmd/generate-request; DO NOT EDIT.

package postcharacterscharacteridassetslocations

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Input struct {
	Character character.Identifier `path:"character_id"`
	Body      []int64              `body:"json" required:"true"`
}
