// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsprojectscontribution

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Input struct {
	Corporation corporation.Identifier `path:"corporation_id"`
	ProjectId   uuid.UUID              `path:"project_id"`
	Character   character.Identifier   `path:"character_id"`
}
