// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridship

import (
	"github.com/eve-online-tools/lib-esi-go/common/item"
	"github.com/eve-online-tools/lib-esi-go/common/typeid"
)

type Output struct {
	ShipItem item.Identifier   `json:"ship_item_id"`
	ShipName string            `json:"ship_name"`
	ShipType typeid.Identifier `json:"ship_type_id"`
}
