// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridship

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/characters/{character_id}/ship",
	request.WithRequiredScope("esi-location.read_ship_type.v1"),
)
