// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidwalletsdivisionjournal

import (
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
)

type Input struct {
	Corporation corporation.Identifier `path:"corporation_id"`
	Division    int64                  `path:"division"`
	Page        *int32                 `query:"page"`
}
