// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridfwstats

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/characters/{character_id}/fw/stats",
	request.WithRequiredScope("esi-characters.read_fw_stats.v1"),
)
