// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsstructuresskyhooksdetail

import (
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
	"github.com/eve-online-tools/lib-esi-go/common/item"
)

type Input struct {
	Skyhook     item.Identifier        `path:"skyhook_id"`
	Corporation corporation.Identifier `path:"corporation_id"`
}
