// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsstructuresskyhooksdetail

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/item"
	"github.com/eve-online-tools/lib-esi-go/common/planet"
	"github.com/eve-online-tools/lib-esi-go/common/typeid"
)

type Output struct {
	EffectiveWorkforce *int64                                                  `json:"effective_workforce"`
	Id                 item.Identifier                                         `json:"id"`
	IsActive           bool                                                    `json:"is_active"`
	Planet             planet.Identifier                                       `json:"planet_id"`
	Reagents           []CorporationsStructuresSkyhooksDetailReagent           `json:"reagents"`
	ReinforcementTimer *CorporationsStructuresSkyhooksDetailReinforcementtimer `json:"reinforcement_timer"`
	State              string                                                  `json:"state"`
	TheftVulnerability *CorporationsStructuresSkyhooksDetailTheftvulnerability `json:"theft_vulnerability"`
}

type CorporationsStructuresSkyhooksDetailReagent struct {
	LastCycle      time.Time         `json:"last_cycle"`
	SecuredStock   int64             `json:"secured_stock"`
	Type           typeid.Identifier `json:"type_id"`
	UnsecuredStock int64             `json:"unsecured_stock"`
}

type CorporationsStructuresSkyhooksDetailReinforcementtimer struct {
	End time.Time `json:"end"`
}

type CorporationsStructuresSkyhooksDetailTheftvulnerability struct {
	End   time.Time `json:"end"`
	Start time.Time `json:"start"`
}
