// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridwalletjournal

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/characters/{character_id}/wallet/journal",
	request.WithRequiredScope("esi-wallet.read_character_wallet.v1"),
)
