// Code generated by cmd/generate-request; DO NOT EDIT.

package getdogmadynamicitemstypeiditemid

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/dogma/dynamic/items/{type_id}/{item_id}",
)
