// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridmailmailid

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/characters/{character_id}/mail/{mail_id}",
	request.WithRequiredScope("esi-mail.read_mail.v1"),
)
