// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsstructuressovereigntyhubslisting

import (
	"github.com/eve-online-tools/lib-esi-go/common/item"
	"github.com/eve-online-tools/lib-esi-go/common/solarsystem"
)

type Output struct {
	SovereigntyHubs []CorporationsStructuresSovereigntyHubsListingSovereigntyhub `json:"sovereignty_hubs"`
}

type CorporationsStructuresSovereigntyHubsListingSovereigntyhub struct {
	Id          item.Identifier        `json:"id"`
	SolarSystem solarsystem.Identifier `json:"solar_system_id"`
}
