// Code generated by cmd/generate-request; DO NOT EDIT.

package getskyhooksraidable

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/planet"
	"github.com/eve-online-tools/lib-esi-go/common/solarsystem"
)

type Output struct {
	Skyhooks []SkyhooksRaidableVulnerableskyhook `json:"skyhooks"`
}

type SkyhooksRaidableTheftvulnerability struct {
	End   time.Time `json:"end"`
	Start time.Time `json:"start"`
}

type SkyhooksRaidableVulnerableskyhook struct {
	Planet             planet.Identifier                  `json:"planet_id"`
	SolarSystem        solarsystem.Identifier             `json:"solar_system_id"`
	TheftVulnerability SkyhooksRaidableTheftvulnerability `json:"theft_vulnerability"`
}
