// Code generated by cmd/generate-request; DO NOT EDIT.

package getskyhooksraidable

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.CreateStatic[*Output](
	http.MethodGet,
	"/skyhooks/raidable",
)
