// Code generated by cmd/generate-request; DO NOT EDIT.

package getcontractspublicbidscontractid

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/contracts/public/bids/{contract_id}",
)
