// Code generated by cmd/generate-request; DO NOT EDIT.

package deletecharacterscharacteridcontacts

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Input struct {
	Character  character.Identifier `path:"character_id"`
	ContactIds []int64              `query:"contact_ids" required:"true"`
}
