// Code generated by cmd/generate-request; DO NOT EDIT.

package getparagonhubskinr

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/character"
	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Output struct {
	Cursor   *Cursor                       `json:"cursor"`
	Listings []ParagonHubSkinrInternalItem `json:"listings"`
}

type Cursor struct {
	After  *string `json:"after"`
	Before *string `json:"before"`
}

type Price struct {
	Isk  *float64 `json:"isk,omitempty"`
	Plex *int64   `json:"plex,omitempty"`
}

type ParagonHubSkinrInternalItem struct {
	Created      time.Time            `json:"created"`
	Expires      time.Time            `json:"expires"`
	Id           uuid.UUID            `json:"id"`
	LastModified time.Time            `json:"last_modified"`
	Price        Price                `json:"price"`
	Quantity     int64                `json:"quantity"`
	Seller       character.Identifier `json:"seller_id"`
	SkinrId      string               `json:"skinr_id"`
	State        string               `json:"state"`
}
