// Code generated by cmd/generate-request; DO NOT EDIT.

package putcharacterscharacteridcontacts

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Input struct {
	Character character.Identifier `path:"character_id"`
	LabelIds  []int64              `query:"label_ids"`
	Standing  float64              `query:"standing" required:"true"`
	Watched   *bool                `query:"watched"`
	Body      []int64              `body:"json" required:"true"`
}
