// Code generated by cmd/generate-request; DO NOT EDIT.

package getcosmeticsskinr

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
	"github.com/eve-online-tools/lib-esi-go/common/typeid"
)

type Output struct {
	Creator  character.Identifier `json:"creator_id"`
	Id       string               `json:"id"`
	Layout   CosmeticsSkinrLayout `json:"layout"`
	Line     *string              `json:"line"`
	Name     string               `json:"name"`
	ShipType typeid.Identifier    `json:"ship_type_id"`
	Tier     CosmeticsSkinrTier   `json:"tier"`
}

type CosmeticsSkinrSlotnanocoating struct {
	Id int64 `json:"id"`
}

type CosmeticsSkinrPatternprojection struct {
	Slot1 bool `json:"slot1"`
	Slot2 bool `json:"slot2"`
	Slot3 bool `json:"slot3"`
	Slot4 bool `json:"slot4"`
}

type CosmeticsSkinrVector3 struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}

type CosmeticsSkinrVector4 struct {
	W float64 `json:"w"`
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}

type CosmeticsSkinrPatterntransform struct {
	Position CosmeticsSkinrVector3 `json:"position"`
	Rotation CosmeticsSkinrVector4 `json:"rotation"`
	Scaling  CosmeticsSkinrVector3 `json:"scaling"`
}

type CosmeticsSkinrPatternconfiguration struct {
	Mirrored   bool                            `json:"mirrored"`
	Projection CosmeticsSkinrPatternprojection `json:"projection"`
	Transform  CosmeticsSkinrPatterntransform  `json:"transform"`
}

type CosmeticsSkinrSlotpattern struct {
	Configuration CosmeticsSkinrPatternconfiguration `json:"configuration"`
	Id            int64                              `json:"id"`
}

type Configuration struct {
	Nanocoating *CosmeticsSkinrSlotnanocoating `json:"nanocoating,omitempty"`
	Pattern     *CosmeticsSkinrSlotpattern     `json:"pattern,omitempty"`
}

type CosmeticsSkinrLayoutslot struct {
	Configuration Configuration `json:"configuration"`
	Id            int64         `json:"id"`
}

type CosmeticsSkinrLayout struct {
	PatternBlendMode string                     `json:"pattern_blend_mode"`
	Slots            []CosmeticsSkinrLayoutslot `json:"slots"`
}

type CosmeticsSkinrTier struct {
	Level int64 `json:"level"`
}
