// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridsearch

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Input struct {
	Categories []string             `query:"categories" required:"true"`
	Character  character.Identifier `path:"character_id"`
	Search     string               `query:"search" required:"true"`
	Strict     *bool                `query:"strict"`
}
