// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridsearch

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/characters/{character_id}/search",
	request.WithRequiredScope("esi-search.search_structures.v1"),
)
