// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidfacilities

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/corporations/{corporation_id}/facilities",
	request.WithRequiredScope("esi-corporations.read_facilities.v1"),
)
