// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersmilitarycampaignsobjectivesparticipation

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Input struct {
	Character   character.Identifier `path:"character_id"`
	ObjectiveId uuid.UUID            `path:"objective_id"`
}
