// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersmilitarycampaignsobjectivesparticipation

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Output struct {
	CampaignId   uuid.UUID `json:"campaign_id"`
	Contributed  int64     `json:"contributed"`
	Id           uuid.UUID `json:"id"`
	IsCommitted  bool      `json:"is_committed"`
	LastModified time.Time `json:"last_modified"`
}
