// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersmilitarycampaignsobjectivesparticipation

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/characters/{character_id}/military-campaigns/objectives/{objective_id}",
	request.WithRequiredScope("esi.activity.char:read"),
)
