// Code generated by cmd/generate-request; DO NOT EDIT.

package getfreelancejobsdetail

import (
	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Input struct {
	JobId uuid.UUID `path:"job_id"`
}
