// Code generated by cmd/generate-request; DO NOT EDIT.

package getfreelancejobsdetail

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/character"
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
	"github.com/eve-online-tools/lib-esi-go/common/solarsystem"
	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Output struct {
	AccessAndVisibility FreelanceJobsDetailAccessandvisibility `json:"access_and_visibility"`
	Configuration       FreelanceJobsDetailConfiguration       `json:"configuration"`
	Contribution        *FreelanceJobsDetailContribution       `json:"contribution"`
	Details             FreelanceJobsDetailDetails             `json:"details"`
	Id                  uuid.UUID                              `json:"id"`
	LastModified        time.Time                              `json:"last_modified"`
	Name                string                                 `json:"name"`
	Progress            FreelanceJobsDetailProgress            `json:"progress"`
	Reward              *FreelanceJobsDetailReward             `json:"reward"`
	State               string                                 `json:"state"`
}

type FreelanceJobsDetailBroadcastlocations struct {
	Id   solarsystem.Identifier `json:"id"`
	Name string                 `json:"name"`
}

type FreelanceJobsDetailRestrictions struct {
	MaximumAge *int64 `json:"maximum_age"`
	MinimumAge *int64 `json:"minimum_age"`
}

type FreelanceJobsDetailAccessandvisibility struct {
	AclProtected       bool                                    `json:"acl_protected"`
	BroadcastLocations []FreelanceJobsDetailBroadcastlocations `json:"broadcast_locations"`
	Restrictions       *FreelanceJobsDetailRestrictions        `json:"restrictions"`
}

type Parameters struct {
}

type FreelanceJobsDetailConfiguration struct {
	Method     string     `json:"method"`
	Parameters Parameters `json:"parameters"`
	Version    int64      `json:"version"`
}

type FreelanceJobsDetailContribution struct {
	ContributionPerParticipantLimit *int64   `json:"contribution_per_participant_limit"`
	MaxCommittedParticipants        int64    `json:"max_committed_participants"`
	RewardPerContribution           *float64 `json:"reward_per_contribution"`
	SubmissionLimit                 *int64   `json:"submission_limit"`
	SubmissionMultiplier            *float64 `json:"submission_multiplier"`
}

type FreelanceJobsDetailCreatorcharacter struct {
	Id   character.Identifier `json:"id"`
	Name string               `json:"name"`
}

type FreelanceJobsDetailCreatorcorporation struct {
	Id   corporation.Identifier `json:"id"`
	Name string                 `json:"name"`
}

type FreelanceJobsDetailCreator struct {
	Character   FreelanceJobsDetailCreatorcharacter   `json:"character"`
	Corporation FreelanceJobsDetailCreatorcorporation `json:"corporation"`
}

type FreelanceJobsDetailDetails struct {
	Career      string                     `json:"career"`
	Created     time.Time                  `json:"created"`
	Creator     FreelanceJobsDetailCreator `json:"creator"`
	Description string                     `json:"description"`
	Expires     *time.Time                 `json:"expires"`
	Finished    *time.Time                 `json:"finished"`
}

type FreelanceJobsDetailProgress struct {
	Current int64 `json:"current"`
	Desired int64 `json:"desired"`
}

type FreelanceJobsDetailReward struct {
	Initial   float64 `json:"initial"`
	Remaining float64 `json:"remaining"`
}
