// Code generated by cmd/generate-request; DO NOT EDIT.

package getfreelancejobsdetail

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/freelance-jobs/{job_id}",
)
