// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsprojectslisting

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Output struct {
	Cursor   *Cursor                             `json:"cursor"`
	Projects []CorporationsProjectsDetailProject `json:"projects"`
}

type Cursor struct {
	After  *string `json:"after"`
	Before *string `json:"before"`
}

type CorporationsProjectsDetailProgress struct {
	Current int64 `json:"current"`
	Desired int64 `json:"desired"`
}

type CorporationsProjectsDetailReward struct {
	Initial   float64 `json:"initial"`
	Remaining float64 `json:"remaining"`
}

type CorporationsProjectsDetailProject struct {
	Id           uuid.UUID                          `json:"id"`
	LastModified time.Time                          `json:"last_modified"`
	Name         string                             `json:"name"`
	Progress     CorporationsProjectsDetailProgress `json:"progress"`
	Reward       *CorporationsProjectsDetailReward  `json:"reward"`
	State        string                             `json:"state"`
}
