// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidcontractscontractiditems

import (
	"github.com/eve-online-tools/lib-esi-go/common/corporation"
)

type Input struct {
	ContractId  int64                  `path:"contract_id"`
	Corporation corporation.Identifier `path:"corporation_id"`
}
