// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersfreelancejobslisting

import (
	"time"

	"github.com/eve-online-tools/lib-esi-go/common/uuid"
)

type Output struct {
	FreelanceJobs []FreelanceJobsDetailFreelancejob `json:"freelance_jobs"`
}

type FreelanceJobsDetailProgress struct {
	Current int64 `json:"current"`
	Desired int64 `json:"desired"`
}

type FreelanceJobsDetailReward struct {
	Initial   float64 `json:"initial"`
	Remaining float64 `json:"remaining"`
}

type FreelanceJobsDetailFreelancejob struct {
	Id           uuid.UUID                   `json:"id"`
	LastModified time.Time                   `json:"last_modified"`
	Name         string                      `json:"name"`
	Progress     FreelanceJobsDetailProgress `json:"progress"`
	Reward       *FreelanceJobsDetailReward  `json:"reward"`
	State        string                      `json:"state"`
}
