// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersfreelancejobslisting

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodGet,
	"/characters/{character_id}/freelance-jobs",
	request.WithRequiredScope("esi-characters.read_freelance_jobs.v1"),
)
