// Code generated by cmd/generate-request; DO NOT EDIT.

package postroute

import (
	"github.com/eve-online-tools/lib-esi-go/common/solarsystem"
)

type Output struct {
	Route []solarsystem.Identifier `json:"route"`
}
