// Code generated by cmd/generate-request; DO NOT EDIT.

package postroute

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](
	http.MethodPost,
	"/route/{origin_system_id}/{destination_system_id}",
)
