// Code generated by cmd/generate-request; DO NOT EDIT.

package postuiopenwindowinformation

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, struct{}](
	http.MethodPost,
	"/ui/openwindow/information",
	request.WithRequiredScope("esi-ui.open_window.v1"),
)
