// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridmail

import (
	"github.com/eve-online-tools/lib-esi-go/common/character"
)

type Input struct {
	Character  character.Identifier `path:"character_id"`
	Labels     []int64              `query:"labels"`
	LastMailId *int64               `query:"last_mail_id"`
}
