// Code generated by cmd/generate-request; DO NOT EDIT.

package postcharacterscharacteridcspa

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, Output](
	http.MethodPost,
	"/characters/{character_id}/cspa",
	request.WithRequiredScope("esi-characters.read_contacts.v1"),
)
