// Code generated by cmd/generate-request; DO NOT EDIT.

package getmarketsstructuresstructureid

import (
	"net/http"

	"github.com/eve-online-tools/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](
	http.MethodGet,
	"/markets/structures/{structure_id}",
	request.WithRequiredScope("esi-markets.structure_markets.v1"),
)
